name : send to master

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Version'
        required: true
        default: '1.0.0'

jobs:

  send_version-master:
    runs-on: ubuntu-latest
    steps:
      - name: Send Version
        uses: peter-evans/repository-dispatch@v1
        with:
          token: ${{ secrets.REPO_ACCESS_TOKEN }}
          repository: steviemul/repository_dispatch_receive
          event-type: new-version-available-master
          client-payload: '{"version": "${{ github.event.inputs.version }}"}'
